import './globals.css';

export const metadata = {
	title: 'Outsourced Accounting & Bookkeeping Services | Smartbooks360',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<link href="https://assets.calendly.com/assets/external/widget.css" rel="stylesheet" />
				<link rel="icon" type="image/x-icon" href="/favicon.ico" />
			</head>
			<body>{children}</body>
		</html>
	);
}
